### PR TITLE
enclose ipv6 literals in brackets

### PR DESCRIPTION
**Pull request by bjmgeek**
workaround for https://github.com/hockeypuck/hockeypuck/issues/30

### CODE REVIEW

**Comment by cmars** [comment]
Thanks for this! Could I trouble you to add a short test for this? Specifically, I'd like to know that net.ResolveTCPAddr can resolve the result of `HkpAddr()` for both IPv4 and IPv6 addresses.

With that test coverage, definitely LGTM.

**Comment by bjmgeek** [comment]
I'm not familiar enough with the test platform.  Do I just make a new recon/peer_test.go file?

**Comment by cmars** [comment]
Yes, that'd be a nice place for it. `recon/messages_test.go` might be a useful example to follow along with.

**Comment by cmars** [comment]
Actually, I've got it. The current tests in master here aren't quite up to date. Will merge shortly.

**Pull request merged**
